version: '3.7'
services:
  api:
    build: .
    container_name: api_imdb
    network_mode: host
    volumes:
      - ./:/app
    env_file:
    - .env
    command: sh -c "yarn install && yarn dev:server"
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on: 
      - "postgres"

  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: host
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=docker
    ports: 
      - 5432:5432